// <auto-generated />
namespace NhaTro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sua_tenqh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sua_tenqh));
        
        string IMigrationMetadata.Id
        {
            get { return "201907230855401_sua_tenqh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
