// <auto-generated />
namespace NhaTro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class them_mota : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_mota));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290231433_them_mota"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
